## You have been hired by a rookie movie producer to help him decide what type of movies to produce and which actors to cast. You have to back your recommendations based on thorough analysis of the data he shared with you which has the list of 3000 movies and the corresponding details.

## As a data scientist, you have to first explore the data and check its sanity.

## Further, you have to answer the following questions:
1. ### <b> Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.</b>
2. ### <b>This data has information about movies made in different languages. Which language has the highest average ROI (return on investment)? </b>
3. ### <b> Find out the unique genres of movies in this dataset.</b>

4. ### <b> Which actor has acted in the most number of movies? Deep dive into the movies, genres and profits corresponding to this actor. </b>

In [ ]:
import pandas as pd

In [ ]:
path = '/content/drive/MyDrive/imdb_data.csv'

df = pd.read_csv(path)

In [ ]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

In [ ]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [ ]:
df['profit'] = df['revenue'] - df['budget']
df.head(2)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435

In [ ]:
df['profit'].max()

1316249360

In [ ]:
df[df['profit'] == df['profit'].max()][['original_title']]

     original_title
1761      Furious 7

In [ ]:
max_profit_row = df[df['profit'] == df['profit'].max()][['original_title']].values[0][0]
max_profit_row

'Furious 7'

In [ ]:
max_profit_row = df[df['profit'] == df['profit'].max()]
max_profit_row

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit
1761,1762,"[{'id': 9485, 'name': 'The Fast and the Furiou...",190000000,"[{'id': 28, 'name': 'Action'}]",http://www.furious7.com/,tt2820852,en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,27.275687,...,137.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Vengeance Hits Home,Furious 7,"[{'id': 830, 'name': 'car race'}, {'id': 3428,...","[{'cast_id': 17, 'character': 'Dominic Toretto...","[{'credit_id': '52fe4cc8c3a36847f823e681', 'de...",1506249360,1316249360

In [ ]:
max_profit_row.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 1761 to 1761
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     1 non-null      int64
 1   belongs_to_collection  1 non-null      object
 2   budget                 1 non-null      int64
 3   genres                 1 non-null      object
 4   homepage               1 non-null      object
 5   imdb_id                1 non-null      object
 6   original_language      1 non-null      object
 7   original_title         1 non-null      object
 8   overview               1 non-null      object
 9   popularity             1 non-null      float64
 10  poster_path            1 non-null      object
 11  production_companies   1 non-null      object
 12  production_countries   1 non-null      object
 13  release_date           1 non-null      object
 14  runtime                1 non-null      float64
 15  spoken_languages       1 non-null      object
 16  status                 1 non-null      object
 17  tagline                1 non-null      object
 18  title                  1 non-null      object
 19  Keywords               1 non-null      object
 20  cast                   1 non-null      object
 21  crew                   1 non-null      object
 22  revenue                1 non-null      int64
 23  profit                 1 non-null      int64
dtypes: float64(2), int64(4), object(18)
memory usage: 200.0+ bytes

In [ ]:
max_profit_row['cast'].values[0]

'[{\'cast_id\': 17, \'character\': \'Dominic Toretto\', \'credit_id\': \'5431dfd10e0a265915002c34\', \'gender\': 2, \'id\': 12835, \'name\': \'Vin Diesel\', \'order\': 0, \'profile_path\': \'/7rwSXluNWZAluYMOEWBxkPmckES.jpg\'}, {\'cast_id\': 19, \'character\': "Brian O\'Conner", \'credit_id\': \'5431dfe4c3a3681143002b98\', \'gender\': 2, \'id\': 8167, \'name\': \'Paul Walker\', \'order\': 1, \'profile_path\': \'/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg\'}, {\'cast_id\': 18, \'character\': \'Hobbs\', \'credit_id\': \'5431dfdbc3a36831a6004376\', \'gender\': 2, \'id\': 18918, \'name\': \'Dwayne Johnson\', \'order\': 2, \'profile_path\': \'/kuqFzlYMc2IrsOyPznMd1FroeGq.jpg\'}, {\'cast_id\': 20, \'character\': \'Letty\', \'credit_id\': \'5431dfeec3a36811ef002c75\', \'gender\': 1, \'id\': 17647, \'name\': \'Michelle Rodriguez\', \'order\': 3, \'profile_path\': \'/v37VK0MNuRuJOCKPKJcZAJXRA5r.jpg\'}, {\'cast_id\': 28, \'character\': \'Roman\', \'credit_id\': \'5431e0310e0a2656e2002c95\', \'gender\': 2, \'id\': 8169, \'name\': \'Tyrese Gibson\', \'order\': 4, \'profile_path\': \'/a3tyF7QXgeEH0QuEuIzNZZ8oLNS.jpg\'}, {\'cast_id\': 31, \'character\': "Tej (as Chris \'Ludacris\' Bridges)", \'credit_id\': \'5431e0520e0a2658b2002c3c\', \'gender\': 2, \'id\': 8171, \'name\': \'Ludacris\', \'order\': 5, \'profile_path\': \'/xLfq9wFO6dtYuUK96hbJ8I8EKFw.jpg\'}, {\'cast_id\': 24, \'character\': \'Mia\', \'credit_id\': \'5431e00dc3a36811ef002c7e\', \'gender\': 1, \'id\': 22123, \'name\': \'Jordana Brewster\', \'order\': 6, \'profile_path\': \'/dORwXZWWmDgG66I5i2Fnr27g3fO.jpg\'}, {\'cast_id\': 25, \'character\': \'Jakande\', \'credit_id\': \'5431e015c3a36831a90040da\', \'gender\': 2, \'id\': 938, \'name\': \'Djimon Hounsou\', \'order\': 7, \'profile_path\': \'/y22Pb0XAVqC0l7ukzKKtXzPEuHk.jpg\'}, {\'cast_id\': 30, \'character\': \'Kiet\', \'credit_id\': \'5431e04a0e0a26464300432c\', \'gender\': 2, \'id\': 57207, \'name\': \'Tony Jaa\', \'order\': 8, \'profile_path\': \'/qq0uXKe3aKaAE04QQ0BvbbFFufF.jpg\'}, {\'cast_id\': 21, \'character\': \'Kara\', \'credit_id\': \'5431dff40e0a2646490043fa\', \'gender\': 0, \'id\': 997887, \'name\': \'Ronda Rousey\', \'order\': 9, \'profile_path\': \'/5eGHTV1bLOdajC4Z3pnIdSiptSG.jpg\'}, {\'cast_id\': 27, \'character\': \'Ramsey\', \'credit_id\': \'5431e026c3a36831ac004333\', \'gender\': 1, \'id\': 1251069, \'name\': \'Nathalie Emmanuel\', \'order\': 10, \'profile_path\': \'/yYiJwunH04doOZJgMu7qTZyrRYJ.jpg\'}, {\'cast_id\': 22, \'character\': \'Mr. Nobody\', \'credit_id\': \'5431dffa0e0a265872002bdf\', \'gender\': 2, \'id\': 6856, \'name\': \'Kurt Russell\', \'order\': 11, \'profile_path\': \'/rlnFuNkisPpuypARI7QaGCmOY6V.jpg\'}, {\'cast_id\': 16, \'character\': \'Deckard Shaw\', \'credit_id\': \'5431dfc70e0a265872002bd5\', \'gender\': 2, \'id\': 976, \'name\': \'Jason Statham\', \'order\': 12, \'profile_path\': \'/PhWiWgasncGWD9LdbsGcmxkV4r.jpg\'}, {\'cast_id\': 39, \'character\': \'Han\', \'credit_id\': \'554fa75f92514110bd002a7d\', \'gender\': 2, \'id\': 61697, \'name\': \'Sung Kang\', \'order\': 13, \'profile_path\': \'/fqt53KEfHWsRDcbV2YAY2lKlKrM.jpg\'}, {\'cast_id\': 38, \'character\': \'Gisele\', \'credit_id\': \'554fa7439251413e40005aa1\', \'gender\': 1, \'id\': 90633, \'name\': \'Gal Gadot\', \'order\': 14, \'profile_path\': \'/34kHAyBaBhq2kUrmhM15paEBuuI.jpg\'}, {\'cast_id\': 15, \'character\': \'Sean Boswell\', \'credit_id\': \'5431dfbb0e0a265915002c2d\', \'gender\': 2, \'id\': 155, \'name\': \'Lucas Black\', \'order\': 15, \'profile_path\': \'/41qZZc6vRVm5ZOoXWfEf5NGoIZR.jpg\'}, {\'cast_id\': 23, \'character\': \'Elena\', \'credit_id\': \'5431e003c3a36811ef002c7c\', \'gender\': 1, \'id\': 73269, \'name\': \'Elsa Pataky\', \'order\': 16, \'profile_path\': \'/c1km2kqasJT9GTISMbBZpp3jbuR.jpg\'}, {\'cast_id\': 35, \'character\': \'Hector\', \'credit_id\': \'554fa677c3a3687b7d002468\', \'gender\': 2, \'id\': 53252, \'name\': \'Noel Gugliemi\', \'order\': 17, \'profile_path\': \'/mI5urNyZJAzIGxelTjBkm624DkB.jpg\'}, {\'cast_id\': 37, \'character\': \'Sheppard\', \'credit_id\': \'554fa6f19251413ea10004fc\', \'gender\': 2, \'id\': 222906, \'name\': \'John Brotherton\', \'order\': 18, \'profile_path\': \'/sE73Zs4q8rugmrFnn9jv2wAEVrI.jpg\'}, {\'cast_id\': 34, \'character\': \'Owen Shaw\', \'credit_id\': \'554fa651c3a3681870005275\', \'gender\': 2, \'id\': 114019, \'name\': \'Luke Evans\', \'order\': 19, \'profile_path\': \'/1d31uDYub8TaLOPWfgX78OotduD.jpg\'}, {\'cast_id\': 36, \'character\': \'Safar\', \'credit_id\': \'554fa6d7c3a3685221000283\', \'gender\': 2, \'id\': 492791, \'name\': \'Ali Fazal\', \'order\': 20, \'profile_path\': \'/AmT132VCz3InJBAQQPJnqqgsQsB.jpg\'}, {\'cast_id\': 145, \'character\': \'Jack\', \'credit_id\': \'59a8b72092514157c601fb92\', \'gender\': 0, \'id\': 1880145, \'name\': \'Miller Kimsey\', \'order\': 21, \'profile_path\': None}, {\'cast_id\': 146, \'character\': \'Jack\', \'credit_id\': \'59a8b72b925141579d020797\', \'gender\': 0, \'id\': 1880146, \'name\': \'Charlie Kimsey\', \'order\': 22, \'profile_path\': None}, {\'cast_id\': 133, \'character\': \'Samantha Hobbs\', \'credit_id\': \'56417cfec3a3685be2001846\', \'gender\': 1, \'id\': 1533850, \'name\': \'Eden Estrella\', \'order\': 23, \'profile_path\': \'/xxzcCrgD38jOyCRlbBA5ksfrN14.jpg\'}, {\'cast_id\': 147, \'character\': \'Letty Fan\', \'credit_id\': \'59a8b787c3a36874d5007d12\', \'gender\': 2, \'id\': 1534800, \'name\': \'Gentry White\', \'order\': 24, \'profile_path\': \'/dzu9JUDSHDXrnit7ZlOnJuRJj1X.jpg\'}, {\'cast_id\': 26, \'character\': \'Female Racer\', \'credit_id\': \'5431e01c0e0a265834002c97\', \'gender\': 1, \'id\': 1364893, \'name\': \'Iggy Azalea\', \'order\': 25, \'profile_path\': \'/KG5skDx5WeGDijkUUQnmOP0crG.jpg\'}, {\'cast_id\': 148, \'character\': \'Male Racer\', \'credit_id\': \'59a8b7afc3a3683d0701b1ad\', \'gender\': 0, \'id\': 1161711, \'name\': \'Jon Lee Brody\', \'order\': 26, \'profile_path\': \'/u1agQE1nYgt2LOijksYJMPYxpKh.jpg\'}, {\'cast_id\': 135, \'character\': \'Race Starter\', \'credit_id\': \'56c259c89251414a9b000865\', \'gender\': 1, \'id\': 1578220, \'name\': \'Levy Tran\', \'order\': 27, \'profile_path\': \'/iKcRuLRwmcuoD43E4X0YlYquYGD.jpg\'}, {\'cast_id\': 132, \'character\': \'Hot Teacher\', \'credit_id\': \'56417cc592514128af001862\', \'gender\': 0, \'id\': 118593, \'name\': \'Anna Colwell\', \'order\': 28, \'profile_path\': \'/qerkK7Z26GttfJ8Sq6xMwhkYLq3.jpg\'}, {\'cast_id\': 149, \'character\': \'Doctor\', \'credit_id\': \'59a8b80e92514157ab0206fc\', \'gender\': 0, \'id\': 1880147, \'name\': \'Viktor Hernandez\', \'order\': 29, \'profile_path\': None}, {\'cast_id\': 150, \'character\': \'Priest\', \'credit_id\': \'59a8b84092514157c601fce8\', \'gender\': 2, \'id\': 80619, \'name\': \'Steve Coulter\', \'order\': 30, \'profile_path\': \'/v1cwS9Ia89pO154Wje3m4IxuI3.jpg\'}, {\'cast_id\': 130, \'character\': \'Merc Tech\', \'credit_id\': \'56417c3092514128a6001a15\', \'gender\': 0, \'id\': 97844, \'name\': \'Robert Pralgo\', \'order\': 31, \'profile_path\': \'/iDPgSaDVhwIItvqa2Wn79oaUzf8.jpg\'}, {\'cast_id\': 151, \'character\': \'Weapons Tech\', \'credit_id\': \'59a8b888c3a3683ce601e3aa\', \'gender\': 0, \'id\': 1381712, \'name\': \'Antwan Mills\', \'order\': 32, \'profile_path\': \'/58nvO2Se7TS0ETUEzHHjJ0MLH5U.jpg\'}, {\'cast_id\': 152, \'character\': \'Billionaire\', \'credit_id\': \'59a8b8bac3a36874d5007ea3\', \'gender\': 0, \'id\': 1880148, \'name\': \'J.J. Phillips\', \'order\': 33, \'profile_path\': None}, {\'cast_id\': 153, \'character\': \'Dominican Priest\', \'credit_id\': \'59a8b8ccc3a3683c8701fa73\', \'gender\': 0, \'id\': 1880149, \'name\': \'Jorge Ferragut\', \'order\': 34, \'profile_path\': None}, {\'cast_id\': 154, \'character\': \'Hana\', \'credit_id\': \'59a8b8e3c3a36874d5007ec7\', \'gender\': 0, \'id\': 1440699, \'name\': \'Sara Sohn\', \'order\': 35, \'profile_path\': \'/8nfPK3sFpHzw0uu66LmTK9HcQ5G.jpg\'}, {\'cast_id\': 155, \'character\': \'Merc Driver (as Ben Blankenship)\', \'credit_id\': \'59a8b904c3a3683c7a02381c\', \'gender\': 0, \'id\': 1093707, \'name\': \'Benjamin Blankenship\', \'order\': 36, \'profile_path\': \'/xl0O9d7xS6XGSRqQl16StOxtkOR.jpg\'}, {\'cast_id\': 156, \'character\': \'DJ\', \'credit_id\': \'59a8b953c3a36876710081c2\', \'gender\': 0, \'id\': 1880150, \'name\': \'D.J. Hapa\', \'order\': 37, \'profile_path\': None}, {\'cast_id\': 140, \'character\': \'DJ\', \'credit_id\': \'58eee68c92514142020018f0\', \'gender\': 0, \'id\': 224092, \'name\': \'T-Pain\', \'order\': 38, \'profile_path\': None}, {\'cast_id\': 157, \'character\': \'Drone Tech\', \'credit_id\': \'59a8b98892514157ee01f2d9\', \'gender\': 2, \'id\': 54792, \'name\': \'Brian Mahoney\', \'order\': 39, \'profile_path\': \'/v6pTsqgOHE5TldFV63Kr44idQNe.jpg\'}, {\'cast_id\': 131, \'character\': \'Jasmine\', \'credit_id\': \'56417c7b92514128a90018fb\', \'gender\': 1, \'id\': 1128522, \'name\': \'Brittney Alger\', \'order\': 40, \'profile_path\': \'/u1eKIGLkK2GTpqFArNxgAMTMhOj.jpg\'}, {\'cast_id\': 158, \'character\': \'Mando\', \'credit_id\': \'59a8b9ad92514157ab020902\', \'gender\': 0, \'id\': 1451616, \'name\': \'Romeo Santos\', \'order\': 41, \'profile_path\': \'/lbt98DkUpRNoJXiFbXzQfhMIRt4.jpg\'}, {\'cast_id\': 159, \'character\': \'Advisor\', \'credit_id\': \'59a8b9ca925141579d020ab6\', \'gender\': 1, \'id\': 78804, \'name\': \'Jocelin Donahue\', \'order\': 42, \'profile_path\': \'/eQXBzPjo9K8MG9TVOoQDNoHEFwv.jpg\'}, {\'cast_id\': 160, \'character\': \'Field Reporter\', \'credit_id\': \'59a8b9da9251415808021296\', \'gender\': 0, \'id\': 1880151, \'name\': \'Stephanie Langston\', \'order\': 43, \'profile_path\': None}, {\'cast_id\': 161, \'character\': \'Cop\', \'credit_id\': \'59a8b9f192514157a5020874\', \'gender\': 0, \'id\': 1448173, \'name\': \'Jorge-Luis Pallo\', \'order\': 44, \'profile_path\': \'/9cw97jnvm7SvnCTNBWZHXt4clfu.jpg\'}, {\'cast_id\': 143, \'character\': \'Leo (uncredited / archive)\', \'credit_id\': \'58eee6b8925141423500180f\', \'gender\': 2, \'id\': 96321, \'name\': \'Tego Calder√≥n\', \'order\': 45, \'profile_path\': \'/pz7i7LV35XRC5Si8liRoYWdrcr0.jpg\'}, {\'cast_id\': 142, \'character\': \'Neela (uncredited / archive)\', \'credit_id\': \'58eee6ab92514141ff001971\', \'gender\': 1, \'id\': 116277, \'name\': \'Nathalie Kelley\', \'order\': 46, \'profile_path\': \'/68xBLk7FvQ36v794LbOrMxeOJeQ.jpg\'}, {\'cast_id\': 29, \'character\': \'Twinkie (uncredited)\', \'credit_id\': \'5431e03e0e0a265872002bf2\', \'gender\': 0, \'id\': 58197, \'name\': \'Shad Moss\', \'order\': 47, \'profile_path\': \'/A1rHY9B5R9cIQshClcJxBYINg1m.jpg\'}, {\'cast_id\': 144, \'character\': \'Santos (uncredited / archive)\', \'credit_id\': \'58eee6c492514141f70019b8\', \'gender\': 0, \'id\': 90634, \'name\': \'Don Omar\', \'order\': 48, \'profile_path\': \'/f1INIG2TE9jXXp5A3gGJR9UkePK.jpg\'}, {\'cast_id\': 141, \'character\': \'Race Wars Racer (uncredited)\', \'credit_id\': \'58eee698c3a36826510017dc\', \'gender\': 0, \'id\': 1563213, \'name\': \'Klement Tinaj\', \'order\': 49, \'profile_path\': None}, {\'cast_id\': 139, \'character\': "Brian O\'Conner (uncredited)", \'credit_id\': \'58eee621c3a368265e001729\', \'gender\': 0, \'id\': 1795034, \'name\': \'Caleb Walker\', \'order\': 50, \'profile_path\': None}, {\'cast_id\': 45, \'character\': "Brian O\'Connor (uncredited)", \'credit_id\': \'5589e3fd925141569c00003e\', \'gender\': 2, \'id\': 1480862, \'name\': \'Cody Walker\', \'order\': 51, \'profile_path\': \'/6InC9qPrftOqsRK9ALcKFLHXSLV.jpg\'}]'

In [ ]:
eval(max_profit_row['cast'].values[0])

[{'cast_id': 17,
  'character': 'Dominic Toretto',
  'credit_id': '5431dfd10e0a265915002c34',
  'gender': 2,
  'id': 12835,
  'name': 'Vin Diesel',
  'order': 0,
  'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'},
 {'cast_id': 19,
  'character': "Brian O'Conner",
  'credit_id': '5431dfe4c3a3681143002b98',
  'gender': 2,
  'id': 8167,
  'name': 'Paul Walker',
  'order': 1,
  'profile_path': '/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg'},
 {'cast_id': 18,
  'character': 'Hobbs',
  'credit_id': '5431dfdbc3a36831a6004376',
  'gender': 2,
  'id': 18918,
  'name': 'Dwayne Johnson',
  'order': 2,
  'profile_path': '/kuqFzlYMc2IrsOyPznMd1FroeGq.jpg'},
 {'cast_id': 20,
  'character': 'Letty',
  'credit_id': '5431dfeec3a36811ef002c75',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 3,
  'profile_path': '/v37VK0MNuRuJOCKPKJcZAJXRA5r.jpg'},
 {'cast_id': 28,
  'character': 'Roman',
  'credit_id': '5431e0310e0a2656e2002c95',
  'gender': 2,
  'id': 8169,
  'name': 'Tyrese Gibson',
  'order': 4,
  'profile_path': '/a3tyF7QXgeEH0QuEuIzNZZ8oLNS.jpg'},
 {'cast_id': 31,
  'character': "Tej (as Chris 'Ludacris' Bridges)",
  'credit_id': '5431e0520e0a2658b2002c3c',
  'gender': 2,
  'id': 8171,
  'name': 'Ludacris',
  'order': 5,
  'profile_path': '/xLfq9wFO6dtYuUK96hbJ8I8EKFw.jpg'},
 {'cast_id': 24,
  'character': 'Mia',
  'credit_id': '5431e00dc3a36811ef002c7e',
  'gender': 1,
  'id': 22123,
  'name': 'Jordana Brewster',
  'order': 6,
  'profile_path': '/dORwXZWWmDgG66I5i2Fnr27g3fO.jpg'},
 {'cast_id': 25,
  'character': 'Jakande',
  'credit_id': '5431e015c3a36831a90040da',
  'gender': 2,
  'id': 938,
  'name': 'Djimon Hounsou',
  'order': 7,
  'profile_path': '/y22Pb0XAVqC0l7ukzKKtXzPEuHk.jpg'},
 {'cast_id': 30,
  'character': 'Kiet',
  'credit_id': '5431e04a0e0a26464300432c',
  'gender': 2,
  'id': 57207,
  'name': 'Tony Jaa',
  'order': 8,
  'profile_path': '/qq0uXKe3aKaAE04QQ0BvbbFFufF.jpg'},
 {'cast_id': 21,
  'character': 'Kara',
  'credit_id': '5431dff40e0a2646490043fa',
  'gender': 0,
  'id': 997887,
  'name': 'Ronda Rousey',
  'order': 9,
  'profile_path': '/5eGHTV1bLOdajC4Z3pnIdSiptSG.jpg'},
 {'cast_id': 27,
  'character': 'Ramsey',
  'credit_id': '5431e026c3a36831ac004333',
  'gender': 1,
  'id': 1251069,
  'name': 'Nathalie Emmanuel',
  'order': 10,
  'profile_path': '/yYiJwunH04doOZJgMu7qTZyrRYJ.jpg'},
 {'cast_id': 22,
  'character': 'Mr. Nobody',
  'credit_id': '5431dffa0e0a265872002bdf',
  'gender': 2,
  'id': 6856,
  'name': 'Kurt Russell',
  'order': 11,
  'profile_path': '/rlnFuNkisPpuypARI7QaGCmOY6V.jpg'},
 {'cast_id': 16,
  'character': 'Deckard Shaw',
  'credit_id': '5431dfc70e0a265872002bd5',
  'gender': 2,
  'id': 976,
  'name': 'Jason Statham',
  'order': 12,
  'profile_path': '/PhWiWgasncGWD9LdbsGcmxkV4r.jpg'},
 {'cast_id': 39,
  'character': 'Han',
  'credit_id': '554fa75f92514110bd002a7d',
  'gender': 2,
  'id': 61697,
  'name': 'Sung Kang',
  'order': 13,
  'profile_path': '/fqt53KEfHWsRDcbV2YAY2lKlKrM.jpg'},
 {'cast_id': 38,
  'character': 'Gisele',
  'credit_id': '554fa7439251413e40005aa1',
  'gender': 1,
  'id': 90633,
  'name': 'Gal Gadot',
  'order': 14,
  'profile_path': '/34kHAyBaBhq2kUrmhM15paEBuuI.jpg'},
 {'cast_id': 15,
  'character': 'Sean Boswell',
  'credit_id': '5431dfbb0e0a265915002c2d',
  'gender': 2,
  'id': 155,
  'name': 'Lucas Black',
  'order': 15,
  'profile_path': '/41qZZc6vRVm5ZOoXWfEf5NGoIZR.jpg'},
 {'cast_id': 23,
  'character': 'Elena',
  'credit_id': '5431e003c3a36811ef002c7c',
  'gender': 1,
  'id': 73269,
  'name': 'Elsa Pataky',
  'order': 16,
  'profile_path': '/c1km2kqasJT9GTISMbBZpp3jbuR.jpg'},
 {'cast_id': 35,
  'character': 'Hector',
  'credit_id': '554fa677c3a3687b7d002468',
  'gender': 2,
  'id': 53252,
  'name': 'Noel Gugliemi',
  'order': 17,
  'profile_path': '/mI5urNyZJAzIGxelTjBkm624DkB.jpg'},
 {'cast_id': 37,
  'character': 'Sheppard',
  'credit_id': '554fa6f19251413ea10004fc',
  'gender': 2,
  'id': 222906,
  'name': 'John Brotherton',
  'order': 18,
  'profile_path': '/sE73Zs4q8rugmrFnn9jv2wAEVrI.jpg'},
 {'cast_id': 34,
  'character': 'Owen Shaw',
  'credit_id': '554fa651c3a3681870005275',
  'gender': 2,
  'id': 114019,
  'name': 'Luke Evans',
  'order': 19,
  'profile_path': '/1d31uDYub8TaLOPWfgX78OotduD.jpg'},
 {'cast_id': 36,
  'character': 'Safar',
  'credit_id': '554fa6d7c3a3685221000283',
  'gender': 2,
  'id': 492791,
  'name': 'Ali Fazal',
  'order': 20,
  'profile_path': '/AmT132VCz3InJBAQQPJnqqgsQsB.jpg'},
 {'cast_id': 145,
  'character': 'Jack',
  'credit_id': '59a8b72092514157c601fb92',
  'gender': 0,
  'id': 1880145,
  'name': 'Miller Kimsey',
  'order': 21,
  'profile_path': None},
 {'cast_id': 146,
  'character': 'Jack',
  'credit_id': '59a8b72b925141579d020797',
  'gender': 0,
  'id': 1880146,
  'name': 'Charlie Kimsey',
  'order': 22,
  'profile_path': None},
 {'cast_id': 133,
  'character': 'Samantha Hobbs',
  'credit_id': '56417cfec3a3685be2001846',
  'gender': 1,
  'id': 1533850,
  'name': 'Eden Estrella',
  'order': 23,
  'profile_path': '/xxzcCrgD38jOyCRlbBA5ksfrN14.jpg'},
 {'cast_id': 147,
  'character': 'Letty Fan',
  'credit_id': '59a8b787c3a36874d5007d12',
  'gender': 2,
  'id': 1534800,
  'name': 'Gentry White',
  'order': 24,
  'profile_path': '/dzu9JUDSHDXrnit7ZlOnJuRJj1X.jpg'},
 {'cast_id': 26,
  'character': 'Female Racer',
  'credit_id': '5431e01c0e0a265834002c97',
  'gender': 1,
  'id': 1364893,
  'name': 'Iggy Azalea',
  'order': 25,
  'profile_path': '/KG5skDx5WeGDijkUUQnmOP0crG.jpg'},
 {'cast_id': 148,
  'character': 'Male Racer',
  'credit_id': '59a8b7afc3a3683d0701b1ad',
  'gender': 0,
  'id': 1161711,
  'name': 'Jon Lee Brody',
  'order': 26,
  'profile_path': '/u1agQE1nYgt2LOijksYJMPYxpKh.jpg'},
 {'cast_id': 135,
  'character': 'Race Starter',
  'credit_id': '56c259c89251414a9b000865',
  'gender': 1,
  'id': 1578220,
  'name': 'Levy Tran',
  'order': 27,
  'profile_path': '/iKcRuLRwmcuoD43E4X0YlYquYGD.jpg'},
 {'cast_id': 132,
  'character': 'Hot Teacher',
  'credit_id': '56417cc592514128af001862',
  'gender': 0,
  'id': 118593,
  'name': 'Anna Colwell',
  'order': 28,
  'profile_path': '/qerkK7Z26GttfJ8Sq6xMwhkYLq3.jpg'},
 {'cast_id': 149,
  'character': 'Doctor',
  'credit_id': '59a8b80e92514157ab0206fc',
  'gender': 0,
  'id': 1880147,
  'name': 'Viktor Hernandez',
  'order': 29,
  'profile_path': None},
 {'cast_id': 150,
  'character': 'Priest',
  'credit_id': '59a8b84092514157c601fce8',
  'gender': 2,
  'id': 80619,
  'name': 'Steve Coulter',
  'order': 30,
  'profile_path': '/v1cwS9Ia89pO154Wje3m4IxuI3.jpg'},
 {'cast_id': 130,
  'character': 'Merc Tech',
  'credit_id': '56417c3092514128a6001a15',
  'gender': 0,
  'id': 97844,
  'name': 'Robert Pralgo',
  'order': 31,
  'profile_path': '/iDPgSaDVhwIItvqa2Wn79oaUzf8.jpg'},
 {'cast_id': 151,
  'character': 'Weapons Tech',
  'credit_id': '59a8b888c3a3683ce601e3aa',
  'gender': 0,
  'id': 1381712,
  'name': 'Antwan Mills',
  'order': 32,
  'profile_path': '/58nvO2Se7TS0ETUEzHHjJ0MLH5U.jpg'},
 {'cast_id': 152,
  'character': 'Billionaire',
  'credit_id': '59a8b8bac3a36874d5007ea3',
  'gender': 0,
  'id': 1880148,
  'name': 'J.J. Phillips',
  'order': 33,
  'profile_path': None},
 {'cast_id': 153,
  'character': 'Dominican Priest',
  'credit_id': '59a8b8ccc3a3683c8701fa73',
  'gender': 0,
  'id': 1880149,
  'name': 'Jorge Ferragut',
  'order': 34,
  'profile_path': None},
 {'cast_id': 154,
  'character': 'Hana',
  'credit_id': '59a8b8e3c3a36874d5007ec7',
  'gender': 0,
  'id': 1440699,
  'name': 'Sara Sohn',
  'order': 35,
  'profile_path': '/8nfPK3sFpHzw0uu66LmTK9HcQ5G.jpg'},
 {'cast_id': 155,
  'character': 'Merc Driver (as Ben Blankenship)',
  'credit_id': '59a8b904c3a3683c7a02381c',
  'gender': 0,
  'id': 1093707,
  'name': 'Benjamin Blankenship',
  'order': 36,
  'profile_path': '/xl0O9d7xS6XGSRqQl16StOxtkOR.jpg'},
 {'cast_id': 156,
  'character': 'DJ',
  'credit_id': '59a8b953c3a36876710081c2',
  'gender': 0,
  'id': 1880150,
  'name': 'D.J. Hapa',
  'order': 37,
  'profile_path': None},
 {'cast_id': 140,
  'character': 'DJ',
  'credit_id': '58eee68c92514142020018f0',
  'gender': 0,
  'id': 224092,
  'name': 'T-Pain',
  'order': 38,
  'profile_path': None},
 {'cast_id': 157,
  'character': 'Drone Tech',
  'credit_id': '59a8b98892514157ee01f2d9',
  'gender': 2,
  'id': 54792,
  'name': 'Brian Mahoney',
  'order': 39,
  'profile_path': '/v6pTsqgOHE5TldFV63Kr44idQNe.jpg'},
 {'cast_id': 131,
  'character': 'Jasmine',
  'credit_id': '56417c7b92514128a90018fb',
  'gender': 1,
  'id': 1128522,
  'name': 'Brittney Alger',
  'order': 40,
  'profile_path': '/u1eKIGLkK2GTpqFArNxgAMTMhOj.jpg'},
 {'cast_id': 158,
  'character': 'Mando',
  'credit_id': '59a8b9ad92514157ab020902',
  'gender': 0,
  'id': 1451616,
  'name': 'Romeo Santos',
  'order': 41,
  'profile_path': '/lbt98DkUpRNoJXiFbXzQfhMIRt4.jpg'},
 {'cast_id': 159,
  'character': 'Advisor',
  'credit_id': '59a8b9ca925141579d020ab6',
  'gender': 1,
  'id': 78804,
  'name': 'Jocelin Donahue',
  'order': 42,
  'profile_path': '/eQXBzPjo9K8MG9TVOoQDNoHEFwv.jpg'},
 {'cast_id': 160,
  'character': 'Field Reporter',
  'credit_id': '59a8b9da9251415808021296',
  'gender': 0,
  'id': 1880151,
  'name': 'Stephanie Langston',
  'order': 43,
  'profile_path': None},
 {'cast_id': 161,
  'character': 'Cop',
  'credit_id': '59a8b9f192514157a5020874',
  'gender': 0,
  'id': 1448173,
  'name': 'Jorge-Luis Pallo',
  'order': 44,
  'profile_path': '/9cw97jnvm7SvnCTNBWZHXt4clfu.jpg'},
 {'cast_id': 143,
  'character': 'Leo (uncredited / archive)',
  'credit_id': '58eee6b8925141423500180f',
  'gender': 2,
  'id': 96321,
  'name': 'Tego Calder√≥n',
  'order': 45,
  'profile_path': '/pz7i7LV35XRC5Si8liRoYWdrcr0.jpg'},
 {'cast_id': 142,
  'character': 'Neela (uncredited / archive)',
  'credit_id': '58eee6ab92514141ff001971',
  'gender': 1,
  'id': 116277,
  'name': 'Nathalie Kelley',
  'order': 46,
  'profile_path': '/68xBLk7FvQ36v794LbOrMxeOJeQ.jpg'},
 {'cast_id': 29,
  'character': 'Twinkie (uncredited)',
  'credit_id': '5431e03e0e0a265872002bf2',
  'gender': 0,
  'id': 58197,
  'name': 'Shad Moss',
  'order': 47,
  'profile_path': '/A1rHY9B5R9cIQshClcJxBYINg1m.jpg'},
 {'cast_id': 144,
  'character': 'Santos (uncredited / archive)',
  'credit_id': '58eee6c492514141f70019b8',
  'gender': 0,
  'id': 90634,
  'name': 'Don Omar',
  'order': 48,
  'profile_path': '/f1INIG2TE9jXXp5A3gGJR9UkePK.jpg'},
 {'cast_id': 141,
  'character': 'Race Wars Racer (uncredited)',
  'credit_id': '58eee698c3a36826510017dc',
  'gender': 0,
  'id': 1563213,
  'name': 'Klement Tinaj',
  'order': 49,
  'profile_path': None},
 {'cast_id': 139,
  'character': "Brian O'Conner (uncredited)",
  'credit_id': '58eee621c3a368265e001729',
  'gender': 0,
  'id': 1795034,
  'name': 'Caleb Walker',
  'order': 50,
  'profile_path': None},
 {'cast_id': 45,
  'character': "Brian O'Connor (uncredited)",
  'credit_id': '5589e3fd925141569c00003e',
  'gender': 2,
  'id': 1480862,
  'name': 'Cody Walker',
  'order': 51,
  'profile_path': '/6InC9qPrftOqsRK9ALcKFLHXSLV.jpg'}]

In [ ]:
a = {'cast_id': 17,
  'character': 'Dominic Toretto',
  'credit_id': '5431dfd10e0a265915002c34',
  'gender': 2,
  'id': 12835,
  'name': 'Vin Diesel',
  'order': 0,
  'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'}

print(a)

{'cast_id': 17, 'character': 'Dominic Toretto', 'credit_id': '5431dfd10e0a265915002c34', 'gender': 2, 'id': 12835, 'name': 'Vin Diesel', 'order': 0, 'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'}

In [ ]:
print(a['name'])

Vin Diesel

In [ ]:
for i in eval(max_profit_row['cast'].values[0]):
  print(i)

{'cast_id': 17, 'character': 'Dominic Toretto', 'credit_id': '5431dfd10e0a265915002c34', 'gender': 2, 'id': 12835, 'name': 'Vin Diesel', 'order': 0, 'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'}
{'cast_id': 19, 'character': "Brian O'Conner", 'credit_id': '5431dfe4c3a3681143002b98', 'gender': 2, 'id': 8167, 'name': 'Paul Walker', 'order': 1, 'profile_path': '/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg'}
{'cast_id': 18, 'character': 'Hobbs', 'credit_id': '5431dfdbc3a36831a6004376', 'gender': 2, 'id': 18918, 'name': 'Dwayne Johnson', 'order': 2, 'profile_path': '/kuqFzlYMc2IrsOyPznMd1FroeGq.jpg'}
{'cast_id': 20, 'character': 'Letty', 'credit_id': '5431dfeec3a36811ef002c75', 'gender': 1, 'id': 17647, 'name': 'Michelle Rodriguez', 'order': 3, 'profile_path': '/v37VK0MNuRuJOCKPKJcZAJXRA5r.jpg'}
{'cast_id': 28, 'character': 'Roman', 'credit_id': '5431e0310e0a2656e2002c95', 'gender': 2, 'id': 8169, 'name': 'Tyrese Gibson', 'order': 4, 'profile_path': '/a3tyF7QXgeEH0QuEuIzNZZ8oLNS.jpg'}
{'cast_id': 31, 'character': "Tej (as Chris 'Ludacris' Bridges)", 'credit_id': '5431e0520e0a2658b2002c3c', 'gender': 2, 'id': 8171, 'name': 'Ludacris', 'order': 5, 'profile_path': '/xLfq9wFO6dtYuUK96hbJ8I8EKFw.jpg'}
{'cast_id': 24, 'character': 'Mia', 'credit_id': '5431e00dc3a36811ef002c7e', 'gender': 1, 'id': 22123, 'name': 'Jordana Brewster', 'order': 6, 'profile_path': '/dORwXZWWmDgG66I5i2Fnr27g3fO.jpg'}
{'cast_id': 25, 'character': 'Jakande', 'credit_id': '5431e015c3a36831a90040da', 'gender': 2, 'id': 938, 'name': 'Djimon Hounsou', 'order': 7, 'profile_path': '/y22Pb0XAVqC0l7ukzKKtXzPEuHk.jpg'}
{'cast_id': 30, 'character': 'Kiet', 'credit_id': '5431e04a0e0a26464300432c', 'gender': 2, 'id': 57207, 'name': 'Tony Jaa', 'order': 8, 'profile_path': '/qq0uXKe3aKaAE04QQ0BvbbFFufF.jpg'}
{'cast_id': 21, 'character': 'Kara', 'credit_id': '5431dff40e0a2646490043fa', 'gender': 0, 'id': 997887, 'name': 'Ronda Rousey', 'order': 9, 'profile_path': '/5eGHTV1bLOdajC4Z3pnIdSiptSG.jpg'}
{'cast_id': 27, 'character': 'Ramsey', 'credit_id': '5431e026c3a36831ac004333', 'gender': 1, 'id': 1251069, 'name': 'Nathalie Emmanuel', 'order': 10, 'profile_path': '/yYiJwunH04doOZJgMu7qTZyrRYJ.jpg'}
{'cast_id': 22, 'character': 'Mr. Nobody', 'credit_id': '5431dffa0e0a265872002bdf', 'gender': 2, 'id': 6856, 'name': 'Kurt Russell', 'order': 11, 'profile_path': '/rlnFuNkisPpuypARI7QaGCmOY6V.jpg'}
{'cast_id': 16, 'character': 'Deckard Shaw', 'credit_id': '5431dfc70e0a265872002bd5', 'gender': 2, 'id': 976, 'name': 'Jason Statham', 'order': 12, 'profile_path': '/PhWiWgasncGWD9LdbsGcmxkV4r.jpg'}
{'cast_id': 39, 'character': 'Han', 'credit_id': '554fa75f92514110bd002a7d', 'gender': 2, 'id': 61697, 'name': 'Sung Kang', 'order': 13, 'profile_path': '/fqt53KEfHWsRDcbV2YAY2lKlKrM.jpg'}
{'cast_id': 38, 'character': 'Gisele', 'credit_id': '554fa7439251413e40005aa1', 'gender': 1, 'id': 90633, 'name': 'Gal Gadot', 'order': 14, 'profile_path': '/34kHAyBaBhq2kUrmhM15paEBuuI.jpg'}
{'cast_id': 15, 'character': 'Sean Boswell', 'credit_id': '5431dfbb0e0a265915002c2d', 'gender': 2, 'id': 155, 'name': 'Lucas Black', 'order': 15, 'profile_path': '/41qZZc6vRVm5ZOoXWfEf5NGoIZR.jpg'}
{'cast_id': 23, 'character': 'Elena', 'credit_id': '5431e003c3a36811ef002c7c', 'gender': 1, 'id': 73269, 'name': 'Elsa Pataky', 'order': 16, 'profile_path': '/c1km2kqasJT9GTISMbBZpp3jbuR.jpg'}
{'cast_id': 35, 'character': 'Hector', 'credit_id': '554fa677c3a3687b7d002468', 'gender': 2, 'id': 53252, 'name': 'Noel Gugliemi', 'order': 17, 'profile_path': '/mI5urNyZJAzIGxelTjBkm624DkB.jpg'}
{'cast_id': 37, 'character': 'Sheppard', 'credit_id': '554fa6f19251413ea10004fc', 'gender': 2, 'id': 222906, 'name': 'John Brotherton', 'order': 18, 'profile_path': '/sE73Zs4q8rugmrFnn9jv2wAEVrI.jpg'}
{'cast_id': 34, 'character': 'Owen Shaw', 'credit_id': '554fa651c3a3681870005275', 'gender': 2, 'id': 114019, 'name': 'Luke Evans', 'order': 19, 'profile_path': '/1d31uDYub8TaLOPWfgX78OotduD.jpg'}
{'cast_id': 36, 'character': 'Safar', 'credit_id': '554fa6d7c3a3685221000283', 'gender': 2, 'id': 492791, 'name': 'Ali Fazal', 'order': 20, 'profile_path': '/AmT132VCz3InJBAQQPJnqqgsQsB.jpg'}
{'cast_id': 145, 'character': 'Jack', 'credit_id': '59a8b72092514157c601fb92', 'gender': 0, 'id': 1880145, 'name': 'Miller Kimsey', 'order': 21, 'profile_path': None}
{'cast_id': 146, 'character': 'Jack', 'credit_id': '59a8b72b925141579d020797', 'gender': 0, 'id': 1880146, 'name': 'Charlie Kimsey', 'order': 22, 'profile_path': None}
{'cast_id': 133, 'character': 'Samantha Hobbs', 'credit_id': '56417cfec3a3685be2001846', 'gender': 1, 'id': 1533850, 'name': 'Eden Estrella', 'order': 23, 'profile_path': '/xxzcCrgD38jOyCRlbBA5ksfrN14.jpg'}
{'cast_id': 147, 'character': 'Letty Fan', 'credit_id': '59a8b787c3a36874d5007d12', 'gender': 2, 'id': 1534800, 'name': 'Gentry White', 'order': 24, 'profile_path': '/dzu9JUDSHDXrnit7ZlOnJuRJj1X.jpg'}
{'cast_id': 26, 'character': 'Female Racer', 'credit_id': '5431e01c0e0a265834002c97', 'gender': 1, 'id': 1364893, 'name': 'Iggy Azalea', 'order': 25, 'profile_path': '/KG5skDx5WeGDijkUUQnmOP0crG.jpg'}
{'cast_id': 148, 'character': 'Male Racer', 'credit_id': '59a8b7afc3a3683d0701b1ad', 'gender': 0, 'id': 1161711, 'name': 'Jon Lee Brody', 'order': 26, 'profile_path': '/u1agQE1nYgt2LOijksYJMPYxpKh.jpg'}
{'cast_id': 135, 'character': 'Race Starter', 'credit_id': '56c259c89251414a9b000865', 'gender': 1, 'id': 1578220, 'name': 'Levy Tran', 'order': 27, 'profile_path': '/iKcRuLRwmcuoD43E4X0YlYquYGD.jpg'}
{'cast_id': 132, 'character': 'Hot Teacher', 'credit_id': '56417cc592514128af001862', 'gender': 0, 'id': 118593, 'name': 'Anna Colwell', 'order': 28, 'profile_path': '/qerkK7Z26GttfJ8Sq6xMwhkYLq3.jpg'}
{'cast_id': 149, 'character': 'Doctor', 'credit_id': '59a8b80e92514157ab0206fc', 'gender': 0, 'id': 1880147, 'name': 'Viktor Hernandez', 'order': 29, 'profile_path': None}
{'cast_id': 150, 'character': 'Priest', 'credit_id': '59a8b84092514157c601fce8', 'gender': 2, 'id': 80619, 'name': 'Steve Coulter', 'order': 30, 'profile_path': '/v1cwS9Ia89pO154Wje3m4IxuI3.jpg'}
{'cast_id': 130, 'character': 'Merc Tech', 'credit_id': '56417c3092514128a6001a15', 'gender': 0, 'id': 97844, 'name': 'Robert Pralgo', 'order': 31, 'profile_path': '/iDPgSaDVhwIItvqa2Wn79oaUzf8.jpg'}
{'cast_id': 151, 'character': 'Weapons Tech', 'credit_id': '59a8b888c3a3683ce601e3aa', 'gender': 0, 'id': 1381712, 'name': 'Antwan Mills', 'order': 32, 'profile_path': '/58nvO2Se7TS0ETUEzHHjJ0MLH5U.jpg'}
{'cast_id': 152, 'character': 'Billionaire', 'credit_id': '59a8b8bac3a36874d5007ea3', 'gender': 0, 'id': 1880148, 'name': 'J.J. Phillips', 'order': 33, 'profile_path': None}
{'cast_id': 153, 'character': 'Dominican Priest', 'credit_id': '59a8b8ccc3a3683c8701fa73', 'gender': 0, 'id': 1880149, 'name': 'Jorge Ferragut', 'order': 34, 'profile_path': None}
{'cast_id': 154, 'character': 'Hana', 'credit_id': '59a8b8e3c3a36874d5007ec7', 'gender': 0, 'id': 1440699, 'name': 'Sara Sohn', 'order': 35, 'profile_path': '/8nfPK3sFpHzw0uu66LmTK9HcQ5G.jpg'}
{'cast_id': 155, 'character': 'Merc Driver (as Ben Blankenship)', 'credit_id': '59a8b904c3a3683c7a02381c', 'gender': 0, 'id': 1093707, 'name': 'Benjamin Blankenship', 'order': 36, 'profile_path': '/xl0O9d7xS6XGSRqQl16StOxtkOR.jpg'}
{'cast_id': 156, 'character': 'DJ', 'credit_id': '59a8b953c3a36876710081c2', 'gender': 0, 'id': 1880150, 'name': 'D.J. Hapa', 'order': 37, 'profile_path': None}
{'cast_id': 140, 'character': 'DJ', 'credit_id': '58eee68c92514142020018f0', 'gender': 0, 'id': 224092, 'name': 'T-Pain', 'order': 38, 'profile_path': None}
{'cast_id': 157, 'character': 'Drone Tech', 'credit_id': '59a8b98892514157ee01f2d9', 'gender': 2, 'id': 54792, 'name': 'Brian Mahoney', 'order': 39, 'profile_path': '/v6pTsqgOHE5TldFV63Kr44idQNe.jpg'}
{'cast_id': 131, 'character': 'Jasmine', 'credit_id': '56417c7b92514128a90018fb', 'gender': 1, 'id': 1128522, 'name': 'Brittney Alger', 'order': 40, 'profile_path': '/u1eKIGLkK2GTpqFArNxgAMTMhOj.jpg'}
{'cast_id': 158, 'character': 'Mando', 'credit_id': '59a8b9ad92514157ab020902', 'gender': 0, 'id': 1451616, 'name': 'Romeo Santos', 'order': 41, 'profile_path': '/lbt98DkUpRNoJXiFbXzQfhMIRt4.jpg'}
{'cast_id': 159, 'character': 'Advisor', 'credit_id': '59a8b9ca925141579d020ab6', 'gender': 1, 'id': 78804, 'name': 'Jocelin Donahue', 'order': 42, 'profile_path': '/eQXBzPjo9K8MG9TVOoQDNoHEFwv.jpg'}
{'cast_id': 160, 'character': 'Field Reporter', 'credit_id': '59a8b9da9251415808021296', 'gender': 0, 'id': 1880151, 'name': 'Stephanie Langston', 'order': 43, 'profile_path': None}
{'cast_id': 161, 'character': 'Cop', 'credit_id': '59a8b9f192514157a5020874', 'gender': 0, 'id': 1448173, 'name': 'Jorge-Luis Pallo', 'order': 44, 'profile_path': '/9cw97jnvm7SvnCTNBWZHXt4clfu.jpg'}
{'cast_id': 143, 'character': 'Leo (uncredited / archive)', 'credit_id': '58eee6b8925141423500180f', 'gender': 2, 'id': 96321, 'name': 'Tego Calder√≥n', 'order': 45, 'profile_path': '/pz7i7LV35XRC5Si8liRoYWdrcr0.jpg'}
{'cast_id': 142, 'character': 'Neela (uncredited / archive)', 'credit_id': '58eee6ab92514141ff001971', 'gender': 1, 'id': 116277, 'name': 'Nathalie Kelley', 'order': 46, 'profile_path': '/68xBLk7FvQ36v794LbOrMxeOJeQ.jpg'}
{'cast_id': 29, 'character': 'Twinkie (uncredited)', 'credit_id': '5431e03e0e0a265872002bf2', 'gender': 0, 'id': 58197, 'name': 'Shad Moss', 'order': 47, 'profile_path': '/A1rHY9B5R9cIQshClcJxBYINg1m.jpg'}
{'cast_id': 144, 'character': 'Santos (uncredited / archive)', 'credit_id': '58eee6c492514141f70019b8', 'gender': 0, 'id': 90634, 'name': 'Don Omar', 'order': 48, 'profile_path': '/f1INIG2TE9jXXp5A3gGJR9UkePK.jpg'}
{'cast_id': 141, 'character': 'Race Wars Racer (uncredited)', 'credit_id': '58eee698c3a36826510017dc', 'gender': 0, 'id': 1563213, 'name': 'Klement Tinaj', 'order': 49, 'profile_path': None}
{'cast_id': 139, 'character': "Brian O'Conner (uncredited)", 'credit_id': '58eee621c3a368265e001729', 'gender': 0, 'id': 1795034, 'name': 'Caleb Walker', 'order': 50, 'profile_path': None}
{'cast_id': 45, 'character': "Brian O'Connor (uncredited)", 'credit_id': '5589e3fd925141569c00003e', 'gender': 2, 'id': 1480862, 'name': 'Cody Walker', 'order': 51, 'profile_path': '/6InC9qPrftOqsRK9ALcKFLHXSLV.jpg'}

In [ ]:
for i in eval(max_profit_row['cast'].values[0]):
  print(i['name'])

Vin Diesel
Paul Walker
Dwayne Johnson
Michelle Rodriguez
Tyrese Gibson
Ludacris
Jordana Brewster
Djimon Hounsou
Tony Jaa
Ronda Rousey
Nathalie Emmanuel
Kurt Russell
Jason Statham
Sung Kang
Gal Gadot
Lucas Black
Elsa Pataky
Noel Gugliemi
John Brotherton
Luke Evans
Ali Fazal
Miller Kimsey
Charlie Kimsey
Eden Estrella
Gentry White
Iggy Azalea
Jon Lee Brody
Levy Tran
Anna Colwell
Viktor Hernandez
Steve Coulter
Robert Pralgo
Antwan Mills
J.J. Phillips
Jorge Ferragut
Sara Sohn
Benjamin Blankenship
D.J. Hapa
T-Pain
Brian Mahoney
Brittney Alger
Romeo Santos
Jocelin Donahue
Stephanie Langston
Jorge-Luis Pallo
Tego Calder√≥n
Nathalie Kelley
Shad Moss
Don Omar
Klement Tinaj
Caleb Walker
Cody Walker

In [ ]:
actor_list = []
for i in eval(max_profit_row['cast'].values[0]):
  actor_list.append(i['name'])
print(actor_list)

['Vin Diesel', 'Paul Walker', 'Dwayne Johnson', 'Michelle Rodriguez', 'Tyrese Gibson', 'Ludacris', 'Jordana Brewster', 'Djimon Hounsou', 'Tony Jaa', 'Ronda Rousey', 'Nathalie Emmanuel', 'Kurt Russell', 'Jason Statham', 'Sung Kang', 'Gal Gadot', 'Lucas Black', 'Elsa Pataky', 'Noel Gugliemi', 'John Brotherton', 'Luke Evans', 'Ali Fazal', 'Miller Kimsey', 'Charlie Kimsey', 'Eden Estrella', 'Gentry White', 'Iggy Azalea', 'Jon Lee Brody', 'Levy Tran', 'Anna Colwell', 'Viktor Hernandez', 'Steve Coulter', 'Robert Pralgo', 'Antwan Mills', 'J.J. Phillips', 'Jorge Ferragut', 'Sara Sohn', 'Benjamin Blankenship', 'D.J. Hapa', 'T-Pain', 'Brian Mahoney', 'Brittney Alger', 'Romeo Santos', 'Jocelin Donahue', 'Stephanie Langston', 'Jorge-Luis Pallo', 'Tego Calder√≥n', 'Nathalie Kelley', 'Shad Moss', 'Don Omar', 'Klement Tinaj', 'Caleb Walker', 'Cody Walker']

In [ ]:
max_profit_row.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 1761 to 1761
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     1 non-null      int64
 1   belongs_to_collection  1 non-null      object
 2   budget                 1 non-null      int64
 3   genres                 1 non-null      object
 4   homepage               1 non-null      object
 5   imdb_id                1 non-null      object
 6   original_language      1 non-null      object
 7   original_title         1 non-null      object
 8   overview               1 non-null      object
 9   popularity             1 non-null      float64
 10  poster_path            1 non-null      object
 11  production_companies   1 non-null      object
 12  production_countries   1 non-null      object
 13  release_date           1 non-null      object
 14  runtime                1 non-null      float64
 15  spoken_languages       1 non-null      object
 16  status                 1 non-null      object
 17  tagline                1 non-null      object
 18  title                  1 non-null      object
 19  Keywords               1 non-null      object
 20  cast                   1 non-null      object
 21  crew                   1 non-null      object
 22  revenue                1 non-null      int64
 23  profit                 1 non-null      int64
dtypes: float64(2), int64(4), object(18)
memory usage: 200.0+ bytes